# Generated by Django 4.1.7 on 2023-03-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemScheduleQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='队列名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='队列编码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统队列',
                'verbose_name_plural': '系统队列',
                'db_table': 'system_schedule_queue',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SystemTaskQueue',
        ),
        migrations.AlterField(
            model_name='systemtask',
            name='task_type',
            field=models.CharField(choices=[('SQL', 'SQL脚本'), ('SHELL', 'Shell脚本'), ('TASK_PRODUCE', '任务生产')], max_length=32, verbose_name='任务类型'),
        ),
    ]
