# Generated by Django 4.1.7 on 2023-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_common_objects', '0002_alter_commoncategory_model_and_more'),
        ('system_task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemtask',
            name='task_type',
        ),
        migrations.AddField(
            model_name='systemtask',
            name='tags',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='django_common_objects.commontag', verbose_name='标签'),
        ),
    ]
