# Generated by Django 4.1.7 on 2023-03-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0002_systemschedulequeue_delete_systemtaskqueue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemschedulequeue',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
