# Generated by Django 4.1.7 on 2023-04-13 16:54

from django.db import migrations, models
import django_common_task_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0003_systemschedulequeue_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemschedulelog',
            name='queue',
            field=models.CharField(default='opening', max_length=100, verbose_name='队列'),
        ),
        migrations.AlterField(
            model_name='systemschedulequeue',
            name='code',
            field=models.CharField(max_length=100, unique=True, validators=[django_common_task_system.models.code_validator], verbose_name='队列编码'),
        ),
        migrations.AlterField(
            model_name='systemschedulequeue',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='配置'),
        ),
    ]
