# Generated by Django 4.1.7 on 2023-04-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0003_systemschedulequeue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemschedulequeue',
            name='module',
            field=models.CharField(choices=[('queue.Queue', '队列'), ('queue.LifoQueue', '栈'), ('queue.PriorityQueue', '优先级队列'), ('_queue.SimpleQueue', '简单队列')], default='queue.Queue', max_length=100, verbose_name='队列类型'),
            preserve_default=False,
        ),
    ]
