# Generated by Django 3.2.18 on 2023-04-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0004_systemschedulelog_queue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemscheduleproducer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='生产名称'),
        ),
    ]
