# Generated by Django 4.1.7 on 2023-04-03 08:05

from django.db import migrations, models
import django_common_task_system.system_task.models


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0004_systemschedulequeue_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemProcess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=100, unique=True, verbose_name='容器ID')),
                ('container_name', models.CharField(max_length=100, unique=True, verbose_name='容器名称')),
                ('env', models.JSONField(default=dict, verbose_name='环境变量')),
                ('status', models.CharField(default='running', max_length=100, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统进程',
                'verbose_name_plural': '系统进程',
                'db_table': 'system_process',
            },
        ),
        migrations.AlterField(
            model_name='systemschedulequeue',
            name='code',
            field=models.CharField(max_length=100, unique=True, validators=[django_common_task_system.system_task.models.code_validator], verbose_name='队列编码'),
        ),
        migrations.AlterField(
            model_name='systemschedulequeue',
            name='module',
            field=models.CharField(choices=[('queue.Queue', '普通队列'), ('queue.LifoQueue', '后进先出队列'), ('queue.PriorityQueue', '优先级队列'), ('_queue.SimpleQueue', '简单队列')], default='queue.Queue', max_length=100, verbose_name='队列类型'),
        ),
        migrations.AlterField(
            model_name='systemtask',
            name='task_type',
            field=models.CharField(choices=[('SQL', 'SQL任务执行'), ('TASK_PRODUCE', 'SQL任务生产'), ('SHELL', 'SHELL任务执行')], default='TASK_PRODUCE', max_length=32, verbose_name='任务类型'),
        ),
    ]
