# Generated by Django 4.1.7 on 2023-04-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0005_alter_systemscheduleproducer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConsumerPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'IP白名单')], default='I', max_length=1, verbose_name='类型')),
                ('status', models.BooleanField(default=True, verbose_name='启用状态')),
                ('config', models.JSONField(blank=True, default=dict, null=True, verbose_name='配置')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('producer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='system_task.systemscheduleproducer', verbose_name='生产者')),
            ],
            options={
                'verbose_name': '消费权限',
                'verbose_name_plural': '消费权限',
                'db_table': 'system_consumer_permission',
                'abstract': False,
                'unique_together': {('producer', 'status')},
            },
        ),
    ]
