# Generated by Django 4.1.7 on 2023-04-21 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0006_systemconsumerpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemExceptionReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '异常报告',
                'verbose_name_plural': '异常报告',
                'db_table': 'system_exception_report',
                'ordering': ('-create_time',),
                'abstract': False,
            },
        ),
    ]
