# Generated by Django 4.1.7 on 2023-05-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0007_systemexceptionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemschedule',
            name='strict_mode',
            field=models.BooleanField(default=False, verbose_name='严格模式'),
        ),
    ]
