# Generated by Django 4.1.7 on 2023-06-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0008_systemschedule_strict_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemschedulecallback',
            name='queue',
        ),
    ]
