# Generated by Django 4.1.7 on 2023-07-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_common_task_system', '0009_taskclient_delete_exceptionreport_customtaskclient_and_more'),
        ('system_task', '0009_remove_systemschedulecallback_queue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemExceptionReport',
            new_name='ExceptionReport',
        ),
        migrations.DeleteModel(
            name='SystemProcess',
        ),
        migrations.CreateModel(
            name='SystemTaskClient',
            fields=[
            ],
            options={
                'verbose_name': '任务客户端',
                'verbose_name_plural': '任务客户端',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_common_task_system.taskclient',),
        ),
        migrations.AlterModelTable(
            name='exceptionreport',
            table='exception_report',
        ),
    ]
