# Generated by Django 4.1.7 on 2023-07-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0010_rename_systemexceptionreport_exceptionreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionreport',
            name='group',
            field=models.CharField(default='user', max_length=100, verbose_name='分组'),
        ),
    ]
