# Generated by Django 4.1.7 on 2023-03-30 06:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_common_task_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskschedule',
            unique_together={('task', 'status', 'user')},
        ),
    ]
