# Generated by Django 4.1.7 on 2023-07-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_common_task_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExceptionReport',
        ),
        migrations.RemoveField(
            model_name='scheduleconsumerpermission',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='scheduleproducer',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='usertaskclient',
            name='taskclient_ptr',
        ),
        migrations.DeleteModel(
            name='ScheduleCallback',
        ),
        migrations.DeleteModel(
            name='ScheduleConsumerPermission',
        ),
        migrations.DeleteModel(
            name='ScheduleProducer',
        ),
        migrations.DeleteModel(
            name='ScheduleQueue',
        ),
        migrations.DeleteModel(
            name='TaskClient',
        ),
        migrations.DeleteModel(
            name='UserTaskClient',
        ),
    ]
