# Generated by Django 4.1.7 on 2023-07-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0001_initial'),
        ('django_common_task_system', '0002_delete_exceptionreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionReport',
            fields=[
            ],
            options={
                'verbose_name': '异常报告',
                'verbose_name_plural': '异常报告',
                'db_table': 'exception_report',
                'ordering': ('-create_time',),
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system_task.exceptionreport',),
        ),
        migrations.CreateModel(
            name='ScheduleCallback',
            fields=[
            ],
            options={
                'verbose_name': '任务回调',
                'verbose_name_plural': '任务回调',
                'db_table': 'schedule_callback',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system_task.schedulecallback',),
        ),
        migrations.CreateModel(
            name='ScheduleConsumerPermission',
            fields=[
            ],
            options={
                'verbose_name': '消费权限',
                'verbose_name_plural': '消费权限',
                'db_table': 'schedule_consumer_permission',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system_task.scheduleconsumerpermission',),
        ),
        migrations.CreateModel(
            name='ScheduleProducer',
            fields=[
            ],
            options={
                'verbose_name': '计划生产',
                'verbose_name_plural': '计划生产',
                'db_table': 'schedule_producer',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system_task.scheduleproducer',),
        ),
        migrations.CreateModel(
            name='ScheduleQueue',
            fields=[
            ],
            options={
                'verbose_name': '任务队列',
                'verbose_name_plural': '任务队列',
                'db_table': 'schedule_queue',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system_task.schedulequeue',),
        ),
        migrations.CreateModel(
            name='UserTaskClient',
            fields=[
            ],
            options={
                'verbose_name': '任务客户端',
                'verbose_name_plural': '任务客户端',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system_task.systemtaskclient',),
        ),
    ]
