# Generated by Django 4.1.7 on 2023-09-06 10:27

from django.db import migrations, models
import django_common_objects.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_common_task_system', '0003_exceptionschedule_alter_taskclient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('state', models.CharField(max_length=100, verbose_name='状态')),
                ('action', models.CharField(max_length=100, verbose_name='操作')),
            ],
            options={
                'verbose_name': '系统总览',
                'verbose_name_plural': '系统总览',
                'ordering': ('name',),
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=django_common_objects.fields.CharField(choices=[('O', '开启'), ('A', '自动'), ('C', '关闭'), ('D', '已完成'), ('T', '测试'), ('E', '调度错误')], default='O', max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='schedulelog',
            name='status',
            field=django_common_objects.fields.CharField(choices=[('I', '初始化'), ('R', '运行中'), ('S', '运行成功'), ('E', '执行成功了，结果为空'), ('N', '无需重试的异常'), ('X', '运行异常'), ('P', '部分失败'), ('F', '任务失败, 无需重试'), ('T', '超时')], max_length=1, verbose_name='运行状态'),
        ),
        migrations.AlterField(
            model_name='schedulequeue',
            name='module',
            field=models.CharField(choices=[('queue.Queue', '先进先出'), ('queue.LifoQueue', '后进先出队列'), ('queue.PriorityQueue', '优先级队列'), ('_queue.SimpleQueue', '简单队列'), ('django_common_task_system.queue.RedisListQueue', 'Redis List队列'), ('multiprocessing.Queue', '多进程队列')], default='queue.Queue', max_length=100, verbose_name='队列类型'),
        ),
    ]
