# Generated by Django 3.2.18 on 2023-04-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_common_task_system', '0004_taskschedulequeue_taskschedulelog_queue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskscheduleproducer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='生产名称'),
        ),
    ]
