# Generated by Django 4.1.7 on 2023-10-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_common_task_system', '0004_overview_alter_schedule_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulequeue',
            name='module',
            field=models.CharField(choices=[('queue.Queue', '先进先出队列'), ('queue.LifoQueue', '后进先出队列'), ('queue.PriorityQueue', '优先级队列'), ('_queue.SimpleQueue', '简单队列'), ('django_common_task_system.queue.RedisFIFOQueue', 'Redis先进先出队列'), ('django_common_task_system.queue.RedisLIFOQueue', 'Redis后进先出队列'), ('multiprocessing.Queue', '多进程队列')], default='queue.Queue', max_length=100, verbose_name='队列类型'),
        ),
    ]
