# Generated by Django 4.1.7 on 2023-04-21 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_common_task_system', '0006_consumerpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '异常报告',
                'verbose_name_plural': '异常报告',
                'db_table': 'task_exception_report',
                'ordering': ('-create_time',),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='taskschedulelog',
            options={'ordering': ('-create_time',), 'verbose_name': '任务日志', 'verbose_name_plural': '任务日志'},
        ),
    ]
