# Generated by Django 4.1.7 on 2023-05-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_common_task_system', '0007_exceptionreport_alter_taskschedulelog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='strict_mode',
            field=models.BooleanField(default=False, verbose_name='严格模式'),
        ),
    ]
