# Generated by Django 4.1.7 on 2023-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_task', '0009_remove_systemschedulecallback_queue'),
        ('django_common_task_system', '0008_taskschedule_strict_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskClient',
            fields=[
                ('group', models.CharField(max_length=100, verbose_name='分组')),
                ('subscription_url', models.CharField(max_length=200, verbose_name='订阅地址')),
                ('subscription_kwargs', models.JSONField(default=dict, verbose_name='订阅参数')),
                ('client_id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='客户端ID')),
                ('process_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='进程ID')),
                ('container_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='容器ID')),
                ('container_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='容器名称')),
                ('container_image', models.CharField(blank=True, max_length=100, null=True, verbose_name='容器镜像')),
                ('container_status', models.CharField(choices=[('None', 'None'), ('Created', 'Created'), ('Paused', 'Paused'), ('Running', 'Running'), ('Restarting', 'Restarting'), ('OOMKilled', 'Oomkilled'), ('Dead', 'Dead'), ('Exited', 'Exited')], default='None', max_length=20, verbose_name='容器状态')),
                ('run_in_container', models.BooleanField(default=True, verbose_name='是否在容器中运行')),
                ('env', models.CharField(blank=True, max_length=500, null=True, verbose_name='环境变量')),
                ('startup_status', models.CharField(choices=[('Init', '初始化'), ('Pulling', '拉取镜像中'), ('Building', '构建中'), ('Running', '启动成功'), ('Failed', '启动失败')], default='Running', max_length=500, verbose_name='启动结果')),
                ('settings', models.TextField(blank=True, null=True, verbose_name='配置')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('startup_log', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': '客户端',
                'verbose_name_plural': '客户端',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ExceptionReport',
        ),
        migrations.CreateModel(
            name='CustomTaskClient',
            fields=[
            ],
            options={
                'verbose_name': '任务客户端',
                'verbose_name_plural': '任务客户端',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_common_task_system.taskclient',),
        ),
        migrations.CreateModel(
            name='ExceptionReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system_task.exceptionreport',),
        ),
    ]
